# Training params
num_train_steps: 50000
log_every_steps: 100
offline: false
batch_size: 32
num_workers: 4
lr: 1e-4
warmup_steps: 5000
decay_steps: 100000

# Model params
img_size: 64
encoder_type: "cnn"
num_slots: 8
slot_size: 64
psb_hidden_dim: 128
inverse_nh: 1
time_nh: 4
obj_nh: 4
num_layers: 2

# Data params
data_dir: "TO DEFINE"
dataset_name: "clevrer"
max_video_len: 301
num_sample_frame: 6
frame_offset: 1