# Training params
num_train_steps: 50000
log_every_steps: 100
offline: false
batch_size: 8
num_workers: 4

# Model params
input_shape: [64, 6, 3, 64, 64]
output_size: 128
num_slots: 8
slot_size: 64
slot_hidden_size: 128
num_layers: 2
time_heads: 4
obj_heads: 4
resolution: [64, 64]