# Training params
num_train_steps: 300000
log_every_steps: 500
offline: false
batch_size: 64
num_workers: 8
lr: 5e-5
warmup_steps: 2500
decay_steps: ${num_train_steps}
checkpoint_every_n_steps: 10000
val_check_interval: 5000

# Model params
img_size: 64
encoder_type: "cnn"
num_slots: 7
slot_size: 64
psb_hidden_dim: 128
inverse_nh: 1
time_nh: 4
obj_nh: 4
num_layers: 2

# Data params
data_dir: "TO DEFINE"
dataset_name: "clevrer"
max_video_len: 128
num_sample_frame: 6
frame_offset: 1